Регистрация
<form action="/user/register" method="post">
    Имя: <input style="width: 300px" type="text" name="name" placeholder="Обязательно для заполнения"> <br>
    Email: <input style="width: 300px" type="text" name="email" placeholder="Обязательно для заполнения"> <br>
    Пароль: <input style="width: 300px" type="password" name="password" placeholder="Обязательно для заполнения"> <br>
    Повторите пароль: <input style="width: 300px" type="password" name="confirmPassword" placeholder="Обязательно для заполнения"> <br>
    <input type="submit" value="Зарегистрироваться">
</form>
<br>
<br>
Войти
<form action="/user/login" method="post">
    email: <input style="width: 300px" type="text" name="email" placeholder="Обязательно для заполнения"> <br>
    Пароль: <input style="width: 300px" type="password" name="password" placeholder="Обязательно для заполнения"> <br>
    <input type="submit" value="Войти">
</form>
<br>
<br>
<?php if($this->error): ?>
    <span style="color: red"><?=$this->error;?><span>
<?php endif;?>